### ISSUE TITLE
Contact Management

### ISSUE THREAD

**Issue by AdelekeAmoo** [Oryx-wa/OryxWebDev#737]
When creating a new contact manager, after feeling the forms it gave an error "Cannot insert the value NULL into column 'Code', table 'PEFHR.CRM.Accounts'; column does not allow nulls. INSERT fails. The statement has been terminated."

On a contact when the edit button is clicked the back button is not working (It can't go back to the list of contact) unless the contact is updated.

**Comment by AdelekeAmoo** [comment]
When the checkbox on the name is clicked, it does not select all the checkbox on the list.

**Comment by BabatundeAlo** [comment]
All Issues have been dealt with
